data = read.csv("C:/Users/Frostless/Downloads/HIV.csv")
table(data)
levels(factor(data$Treatment))
levels(factor(data$Response))
data$Response = relevel(factor(data$Response) , ref = "No HIV")
data$Treatment= relevel(factor(data$Treatment), ref = "Placebo")
levels(factor(data$Treatment))
levels(factor(data$Response))
m1 = glm(data$Response~data$Treatment , family = binomial(link = "logit"))
#summary(m1)
coef(m1)
data$Response = relevel(factor(data$Response) , ref = "No HIV")
m2 = glm(data$Response~data$Treatment , family = binomial(link = "logit"))
#summary(m2)
coef(m2)
p1 = predict(m1)
head(p1,3)
tail(p1 ,3)
p2 = predict(m1 , type = "response")
head(p2,3)
tail(p2,3)
