---
title: "Exercise section 16"
author: "Mehrab Atighi"
date: "5/11/2021"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# section 16:
## 1)
```{r}
library(heplots)
data(RootStock)
data<-as.data.frame(RootStock)
group<-as.factor(data$rootstock)
response<-cbind(RootStock$girth4,RootStock$ext4,RootStock$girth15,RootStock$weight15)
summary(manova(response~group))
means<-data.frame(
mu1<-colMeans(data[1:8,2:5]),
mu2<-colMeans(data[9:16,2:5]),
mu3<-colMeans(data[17:24,2:5]),
mu4<-colMeans(data[25:32,2:5]),
mu5<-colMeans(data[33:40,2:5]),
mu6<-colMeans(data[41:48,2:5])
)
View(means)
colSums(means)
```


## 2)
### a)

H0 : mu1 = mu2 = mu3
H1 : At least one of the means is not equal

### b)
```{r}
M1y1<-c(5.4,5.2,6.1,4.8,5.0,5.7,6.0,4.0,5.7,5.6,5.8,5.3)
M1y2<-c(6,6.2,5.9,5,5.7,6.1,6,5,5.4,5.2,6.1,5.9)
M1y3<-c(6.3,6,6,4.9,5,6,5.8,4,4.9,5.4,5.2,5.8)
M1y4<-c(6.7,5.8,7,5,6.5,6.6,6,5,5,5.8,6.4,6)
M2y1<-c(5,4.8,3.9,4,5.6,6,5.2,5.3,5.9,6.1,6.2,5.1)
M2y2<-c(5.3,4.9,4,5.1,5.4,5.5,4.8,5.1,6.1,6,5.7,4.9)
M2y3<-c(5.3,4.2,4.4,4.8,5.1,5.7,5.4,5.8,5.7,6.1,5.9,5.3)
M2y4<-c(6.5,5.6,5.0,5.8,6.2,6.0,6,6.4,6,6.2,6,4.8)
M3y1<-c(4.8,5.4,4.9,5.7,4.2,6,5.1,4.8,5.3,4.6,4.5,4.4)
M3y2<-c(5,5,5.1,5.2,4.6,5.3,5.2,4.6,5.4,4.4,4.0,4.2)
M3y3<-c(6.5,6,5.9,6.4,5.3,5.8,6.2,5.7,6.8,5.7,5,5.6)
M3y4<-c(7,6.4,6.5,6.4,6.3,6.4,6.5,5.7,6.6,5.6,5.9,5.5)

Method<-factor(rep(c(1:3), each = 48))
variable<-factor(rep(c(1:12),12))
response<-c(M1y1,M1y2,M1y3,M1y4,M2y1,M2y2,M2y3,M2y4,M3y1,M3y2,M3y3,M3y4)
result<-aov(response~Method+variable)
summary(result)
```

### c)
for y1:
method1:
```{r}
response<-c(M1y1,M2y1,M3y1)
group<-factor(rep(1:3,each = 12))
result<-aov(response~group)
summary(result)
```
method2:
```{r}
data<-cbind(response,group)
r<-oneway.test(response~group , data = data ,var.equal = TRUE)
r
```
for y2:
method1:
```{r}
response<-c(M1y2,M2y2,M3y2)
group<-factor(rep(1:3,each = 12))
result<-aov(response~group)
summary(result)
```
method2:
```{r}
data<-cbind(response,group)
r<-oneway.test(response~group , data = data ,var.equal = TRUE)
r
```
for y3:
method1:
```{r}
response<-c(M1y3,M2y3,M3y3)
group<-factor(rep(1:3,each = 12))
result<-aov(response~group)
summary(result)
```
method2:
```{r}
data<-cbind(response,group)
r<-oneway.test(response~group , data = data ,var.equal = TRUE)
r
```

for y4:
method1:
```{r}
response<-c(M1y4,M2y4,M3y4)
group<-factor(rep(1:3,each = 12))
result<-aov(response~group)
summary(result)
```
method2:
```{r}
data<-cbind(response,group)
r<-oneway.test(response~group , data = data ,var.equal = TRUE)
r
```
### d)
for each test we have alpha = 0.05 and
when we use 4 test total error will be 4*0.05 = 0.2 
so its better that we use 1 manova our multiple anova test just with 0.05 error.
